services:
  - type: web
    name: Pixel
    env: python
    region: virginia
    buildCommand: |
      pip install -r requirements.txt
    startCommand: |
      python3 main.py
    envVars:
      - key: NEW_BOT_TOKEN
        value: "{{secrets.NEW_BOT_TOKEN}}"
    plan: free
    healthCheckPath: "/health"
    autoDeploy: true
