services:
  - type: web
    name: Pixel
    env: python
    region: virginia
    buildCommand: |
      pip install -r requirements.txt
    startCommand: |
      python3 main.py
    envVars:
      - key: DISCORD_TOKEN
        sync: false 
      - key: AWS_ACCESS_KEY_ID
        sync: false
      - key: AWS_SECRET_ACCESS_KEY
        sync: false
      - key: AWS_S3_BUCKET
        sync: false
      - key: AWS_S3_REGION
        sync: false
    plan: free
    healthCheckPath: "/health"
    autoDeploy: true
